version: '3'

services:
  formatter:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "pylint **/*.py && exit 0"]

  linter:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "pylint **/*.py"]

  tester:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["pytest"]
